### API USUARIO - GET
GET http://localhost:8080/api/v1/usuarios

### API USUARIO - POST
POST http://localhost:8080/api/v1/usuarios
Content-Type: application/json

{
    "nome": "Sérgio",
    "email": "sergio@gmail.com",
    "renda": 1400
}


### API USUARIO - PUT
PUT http://localhost:8080/api/v1/usuarios/3
Content-Type: application/json

{
    "nome": "Sérgio",
    "email": "sergio@gmail.com",
    "renda": 1400.0
}


### API USUARIO - DELETE
DELETE http://localhost:8080/api/v1/usuarios/2

# ----------------------- #

### API NOTIFICACAO - GET
GET http://localhost:8080/api/v1/notificacoes

### API NOTIFICACAO - POST
POST http://localhost:8080/api/v1/notificacoes
Content-Type: application/json

{
    "mensagem": "Pague sua conta",
    "data": "2025-05-05",
    "usuario": {
        "id" : 1
    }
}

### API NOTIFICACAO - PUT
PUT http://localhost:8080/api/v1/notificacoes/1
Content-Type: application/json

{
    "mensagem": "Pague sua conta IMEDIATAMENTE!",
    "data": "2025-05-05",
    "usuario": {
        "id" : 1
    }
}

### API NOTIFICACAO - DELETE
DELETE http://localhost:8080/api/v1/notificacoes/1

# ----------------------- #

### API DESPESA - GET
GET http://localhost:8080/api/v1/despesas

### API DESPESA - POST
POST http://localhost:8080/api/v1/despesas
Content-Type: application/json

{
    "descricao": "Conta de Luz",
    "valor": 399.99,
    "dataVencimento": "2025-06-01",
    "usuariosResponsaveis": [
  {
    "id": 1
  }
]
}

### API DESPESA - PUT
PUT http://localhost:8080/api/v1/despesas/1
Content-Type: application/json

{
    "descricao": "Conta de Luz",
    "valor": 600,
    "dataVencimento": "2025-07-01",
    "usuariosResponsaveis": [
  {
    "id": 1
  }
]
}

### API DESPESA - DELETE
DELETE http://localhost:8080/api/v1/despesas/1