@startuml
package br.univille.projfabsoft_despesas.entity {
    class GrupoFamiliar {
        - Long id
        - String nome
        - List<Usuario> usuarios
        --
        + Long getId()
        + void setId(Long id)
        + String getNome()
        + void setNome(String nome)
        + List<Usuario> getUsuarios()
        + void setUsuarios(List<Usuario> usuarios)
    }

    class Usuario {
        - Long id
        - String nome
        - Double renda
        - List<Despesa> despesas
        --
        + Long getId()
        + void setId(Long id)
        + String getNome()
        + void setNome(String nome)
        + Double getRenda()
        + void setRenda(Double renda)
        + List<Despesa> getDespesas()
        + void setDespesas(List<Despesa> despesas)
    }

    class Despesa {
        - Long id
        - String descricao
        - Double valor
        - LocalDate dataVencimento
        - List<Usuario> usuariosResponsaveis
        --
        + Long getId()
        + void setId(Long id)
        + String getDescricao()
        + void setDescricao(String descricao)
        + Double getValor()
        + void setValor(Double valor)
        + LocalDate getDataVencimento()
        + void setDataVencimento(LocalDate dataVencimento)
        + List<Usuario> getUsuariosResponsaveis()
        + void setUsuariosResponsaveis(List<Usuario> usuariosResponsaveis)
    }

    class Notificacao {
        - Long id
        - String mensagem
        - LocalDate data
        - Usuario usuario
        - Despesa despesa
        --
        + Long getId()
        + void setId(Long id)
        + String getMensagem()
        + void setMensagem(String mensagem)
        + LocalDate getData()
        + void setData(LocalDate data)
        + Usuario getUsuario()
        + void setUsuario(Usuario usuario)
        + Despesa getDespesa()
        + void setDespesa(Despesa despesa)
    }

    GrupoFamiliar "1" *-- "0..*" Usuario
    Usuario "1" *-- "0..*" Despesa
    Despesa "1" *-- "0..*" Usuario
    Notificacao "1" --> "1" Usuario
    Notificacao "1" --> "1" Despesa
}
@enduml